apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: saleway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            ['sh', '-c', 'until pg_isready -h postgres -U postgres; do echo waiting for database; sleep 2; done;']
      containers:
        - name: cart-service
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ['ALL']
          image: saleway-cart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: saleway-config
            - secretRef:
                name: saleway-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '256Mi'
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
  namespace: saleway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: saleway
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
