"""add_product_indices

Revision ID: 78d96606884c
Revises: 080ff75fe8a8
Create Date: 2026-03-06 23:21:40.642726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78d96606884c'
down_revision: Union[str, Sequence[str], None] = '080ff75fe8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    # ### end Alembic commands ###
