[project]
name = "product"
version = "0.1.0"
description = "A product microservice for a fake e-commerce website."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "fastapi>=0.115.6",
    "loguru>=0.7.3",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.0",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.36.1",
    "poethepoet>=0.38.0",
    "ruff>=0.14.8",
]

[tool.poe.tasks]
start = "uvicorn app:app"
dev = "uvicorn app:app --reload"
venv-create = "uv venv"
venv-activate = "source .venv/bin/activate"
sync = "uv sync"
typecheck = "basedpyright ."
update = "uv lock --upgrade"
format = "ruff format ."
lint = "ruff check --fix ."
migrate = "alembic upgrade head"
create-migration = "alembic revision --autogenerate -m"
seed = "uv run seed.py"
create-db = "psql -U vikiru -h localhost -p 5433 -d postgres -c \"CREATE DATABASE product_service;\""

# FastAPI Service Startup Process:
# 1) source .venv/bin/activate  # Activate virtual environment
# 2) uv sync                     # Install Python packages
# 3) poe create-db               # Create PostgreSQL database (if not already)
# 4) poe migrate                 # Run Alembic migrations
# 5) poe seed                    # Seed database with sample data
# 6) poe dev                     # Start development server
#    or poe start                # Start production server

[tool.ruff]
line-length = 120
fix = true
extend-exclude = ["alembic/versions/"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501", "W291"]

[tool.ruff.lint.isort]
known-first-party = ["services"]
known-third-party = ["sqlmodel", "pydantic", "dotenv", "google_genai", "loguru", "uvicorn"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"
line-ending = "lf"
skip-magic-trailing-comma = false
