[project]
name = "user"
version = "0.1.0"
description = "A user microservice for a fake e-commerce website."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "bcrypt",
  "django",
  "django-allauth",
  "django-cors-headers",
  "django-environ",
  "django-extensions",
  "django-ninja",
  "psycopg2-binary",
  "requests",
  "pydantic",
  "gunicorn>=23.0.0",
  "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "poethepoet>=0.38.0",
    "ruff>=0.14.8",
]

[tool.poe.tasks]
start = "uv run gunicorn user.wsgi --workers 4"
dev = "uv run python manage.py runserver --settings=user.settings --traceback"
venv-create = "uv venv"
venv-activate = "source .venv/bin/activate"
sync = "uv sync"
typecheck = "basedpyright ."
update = "uv lock --upgrade"
format = "ruff format ."
lint = "ruff check --fix ."
init-db = "uv run manage.py migrate"
create-migrations = "uv run manage.py makemigrations"
reset-db = "sh -c 'uv run manage.py flush --noinput && uv run manage.py migrate'"

[tool.ruff]
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501", "W291"]

[tool.ruff.lint.isort]
known-first-party = ["services"]
known-third-party = ["bcrypt", "django", "allauth", "corsheaders", "environ", "extensions", "ninja", "psycopg2", "requests", "pydantic"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"
line-ending = "lf"
skip-magic-trailing-comma = false
