# Generated by Django 5.1.1 on 2024-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
