# Generated by Django 6.0 on 2026-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_clerk_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecommerceuser",
            name="clerk_user_id",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ecommerceuser",
            name="password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
