# Generated by Django 5.1.1 on 2024-10-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('date_purchased', models.DateTimeField()),
            ],
        ),
    ]
