# Generated by Django 5.1.1 on 2024-10-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='date_reviewed',
            field=models.DateTimeField(),
        ),
    ]
