# Generated by Django 6.0 on 2026-03-13 22:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_alter_userreview_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="date_reviewed",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="product_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
