apiVersion: v1
kind: Secret
metadata:
  name: saleway-secrets
  namespace: ecommerce
type: Opaque
stringData:
  # ---------------------------------------------------------
  # PostgreSQL Credentials (for StatefulSet & Microservices)
  # ---------------------------------------------------------
  POSTGRES_ADMIN_PASSWORD: "example_postgres_admin_password"
  CART_DB_PASSWORD: "example_cart_db_password"
  ORDER_DB_PASSWORD: "example_order_db_password"
  PRODUCT_DB_PASSWORD: "example_product_db_password"
  RATING_DB_PASSWORD: "example_rating_db_password"
  USER_DB_PASSWORD: "example_user_db_password"

  # ---------------------------------------------------------
  # Third-Party API Keys
  # ---------------------------------------------------------
  CLERK_SECRET_KEY: "sk_test_example..."
  STRIPE_SECRET_KEY: "sk_test_example..."
  STRIPE_WEBHOOK_SECRET: "whsec_example..."
  STRIPE_PUBLISHABLE_KEY: "pk_test_example..."
